### ISSUE TITLE
New major version required

### ISSUE THREAD

**Issue by jagmit** [google/platform.dart#39]
The removal of `Platform.packageRoot` urgently requires a new major version IMHO as also discussed in https://github.com/google/platform.dart/pull/38 because apps (transitively) depending on it might not build now with the latest flutter stable. 

For example [`path_provider`](https://pub.dev/packages/path_provider) depends on `platform` via `path_provider_platform_interface` in the form of [`platform: ^3.0.0`](https://github.com/flutter/plugins/blob/f7138f7222856623796c2ee2e561f866fcf08d38/packages/path_provider/path_provider_platform_interface/pubspec.yaml#L16). If pub resolves this with `3.0.1` a build error will happen with Dart 2.16 (flutter stable) because `dart:io`'s `Platform.packageRoot` got removed. 

I'm sure there are more examples like this.

cc @mit-mit

**Comment by mit-mit** [comment]
Apps will build with the latest Flutter stable, but they do need to upgrade their dependencies (`flutter pub upgrade` or `flutter pub upgrade --major-versions`).

The is a general issue, as Flutter "pins" to specific package versions (not version ranges), e.g. here for platform:
https://github.com/flutter/flutter/blob/2.10.0/packages/flutter/pubspec.yaml#L33

**Comment by mit-mit** [comment]
Here's the resolution I got:

```
  path_provider:
    dependency: "direct main"
    description:
      name: path_provider
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8"
  path_provider_android:
    dependency: transitive
    description:
      name: path_provider_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.11"
  path_provider_ios:
    dependency: transitive
    description:
      name: path_provider_ios
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.7"
  path_provider_linux:
    dependency: transitive
    description:
      name: path_provider_linux
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5"
  path_provider_macos:
    dependency: transitive
    description:
      name: path_provider_macos
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  path_provider_platform_interface:
    dependency: transitive
    description:
      name: path_provider_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  path_provider_windows:
    dependency: transitive
    description:
      name: path_provider_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  platform:
    dependency: transitive
    description:
      name: platform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.0"
 ```
